-- units.lua – minimal unit definitions for MiniStar
-- All units use simple colored textures generated by the engine.

local unitDefs = {}

-- Command Centre (player base)
unitDefs["command_center"] = {
    name = "Command Center",
    description = "Main base building, produces workers",
    maxdamage = 2000,
    buildcostenergy = 0,
    buildcostmetal = 500,
    buildtime = 3000,
    category = "BUILDING",
    footprintX = 6,
    footprintZ = 6,
    sightDistance = 500,
    canBeAssisted = true,
    canMove = false,
    canAttack = false,
    builder = true,
    buildoptions = {"worker"},
    customParams = {texture = "command_center"},
    script = "command_center.lua",
    objectname = "command_center.s3o",
    -- The engine will generate a simple placeholder model if the file is missing.
}

-- Worker unit (gathers minerals)
unitDefs["worker"] = {
    name = "Worker",
    description = "Collects resources and builds structures",
    maxdamage = 100,
    buildcostenergy = 0,
    buildcostmetal = 50,
    buildtime = 300,
    category = "LAND",
    footprintX = 1,
    footprintZ = 1,
    sightDistance = 200,
    movementClass = "KBOT2",
    maxVelocity = 2.5,
    acceleration = 0.5,
    canAttack = false,
    builder = true,
    buildoptions = {"barracks", "supply_depot"},
    harvesters = 1,
    buildrange = 120,
    customParams = {texture = "worker"},
    script = "worker.lua",
    objectname = "worker.s3o",
}

-- Barracks (produces soldiers)
unitDefs["barracks"] = {
    name = "Barracks",
    description = "Trains Marines and Medics",
    maxdamage = 800,
    buildcostmetal = 300,
    buildtime = 1500,
    category = "BUILDING",
    footprintX = 4,
    footprintZ = 4,
    sightDistance = 300,
    builder = true,
    buildoptions = {"marine", "medic"},
    customParams = {texture = "barracks"},
    script = "barracks.lua",
    objectname = "barracks.s3o",
}

-- Marine (basic combat unit)
unitDefs["marine"] = {
    name = "Marine",
    description = "Basic infantry",
    maxdamage = 150,
    buildcostenergy = 0,
    buildcostmetal = 100,
    buildtime = 500,
    category = "LAND",
    footprintX = 1,
    footprintZ = 1,
    sightDistance = 300,
    movementClass = "KBOT2",
    maxVelocity = 3.0,
    acceleration = 0.7,
    canAttack = true,
    weaponDefs = {
        laser = {
            name = "Laser",
            damage = { default = 25 },
            range = 200,
            reloadtime = 1.0,
            weaponType = "LaserCannon",
        },
    },
    weapons = {
        { def = "laser" },
    },
    customParams = {texture = "marine"},
    script = "marine.lua",
    objectname = "marine.s3o",
}

-- Supply Depot (increases supply limit)
unitDefs["supply_depot"] = {
    name = "Supply Depot",
    description = "Provides additional supply",
    maxdamage = 500,
    buildcostenergy = 0,
    buildcostmetal = 100,
    buildtime = 800,
    category = "BUILDING",
    footprintX = 3,
    footprintZ = 3,
    sightDistance = 250,
    customParams = { texture = "supply_depot" },
    script = "supply_depot.lua",
    objectname = "supply_depot.s3o",
}

-- unit definitions (see below)

-- Additional units and buildings for a richer RTS experience

-- Refinery – produces gas (resource type not used in this minimal demo but placeholder)
unitDefs["refinery"] = {
    name = "Refinery",
    description = "Extracts gas",
    maxdamage = 600,
    buildcostenergy = 0,
    buildcostmetal = 150,
    buildtime = 1200,
    category = "BUILDING",
    footprintX = 4,
    footprintZ = 4,
    sightDistance = 250,
    customParams = {texture = "refinery"},
    script = "refinery.lua",
    objectname = "refinery.s3o",
}

-- Factory – builds heavy vehicles (e.g., Tanks)
unitDefs["factory"] = {
    name = "Factory",
    description = "Builds heavy vehicles (Tanks, Siege Tanks) and aircraft",
    maxdamage = 1000,
    buildcostmetal = 400,
    buildtime = 2000,
    category = "BUILDING",
    footprintX = 6,
    footprintZ = 6,
    sightDistance = 300,
    builder = true,
    buildoptions = {"tank", "siege_tank", "fighter"},
    customParams = {texture = "factory"},
    script = "factory.lua",
    objectname = "factory.s3o",
}

-- Tank – heavy armored combat unit
unitDefs["tank"] = {
    name = "Tank",
    description = "Heavy artillery vehicle",
    maxdamage = 300,
    buildcostenergy = 0,
    buildcostmetal = 250,
    buildtime = 800,
    category = "LAND",
    footprintX = 2,
    footprintZ = 2,
    sightDistance = 350,
    movementClass = "TANK2",
    maxVelocity = 1.8,
    acceleration = 0.4,
    canAttack = true,
    weaponDefs = {
        cannon = {
            name = "Cannon",
            damage = { default = 45 },
            range = 250,
            reloadtime = 2.0,
            weaponType = "Cannon",
        },
    },
    weapons = {
        { def = "cannon" },
    },
    customParams = {texture = "tank"},
    script = "tank.lua",
    objectname = "tank.s3o",
    explosionGenerator = "explosion.s3e",
}

-- Zergling – fast melee unit (for a “Zerg” flavor)
unitDefs["zergling"] = {
    name = "Zergling",
    description = "Fast melee attacker",
    maxdamage = 80,
    buildcostenergy = 0,
    buildcostmetal = 30,
    buildtime = 150,
    category = "LAND",
    footprintX = 1,
    footprintZ = 1,
    sightDistance = 180,
    movementClass = "KBOT2",
    maxVelocity = 4.5,
    acceleration = 1.0,
    canAttack = true,
    weaponDefs = {
        claws = {
            name = "Claws",
            damage = { default = 15 },
            range = 30,
            reloadtime = 0.5,
            weaponType = "Melee",
        },
    },
    weapons = {
        { def = "claws" },
    },
    customParams = {texture = "zergling"},
    script = "zergling.lua",
    objectname = "zergling.s3o",
}
unitDefs["fighter"] = {
    name = "Fighter",
    description = "Fast air unit – simple laser attack",
    maxdamage = 80,
    buildcostmetal = 120,
    buildtime = 800,
    category = "AIR",
    footprintX = 2,
    footprintZ = 2,
    sightDistance = 250,
    movementClass = "AIR",
    maxVelocity = 6.0,
    acceleration = 1.2,
    canAttack = true,
    weaponDefs = {
        laser = {
            name = "Air Laser",
            damage = {default = 20},
            range = 180,
            reloadtime = 0.8,
            weaponType = "LaserCannon",
        },
    },
    weapons = {{def = "laser"}},
    customParams = {texture = "fighter"},
    script = "fighter.lua",
    objectname = "fighter.s3o",
}

unitDefs["medic"] = {
    name = "Medic",
    description = "Heals friendly units",
    maxdamage = 60,
    buildcostmetal = 80,
    buildtime = 400,
    category = "LAND",
    footprintX = 1,
    footprintZ = 1,
    sightDistance = 150,
    movementClass = "KBOT2",
    maxVelocity = 2.0,
    acceleration = 0.5,
    canAttack = false,
    weaponDefs = {
        heal = {
            name = "Heal Beam",
            damage = {default = 0},
            range = 120,
            reloadtime = 1.0,
            weaponType = "LaserCannon",  -- we'll use a healing effect via script
        },
    },
    weapons = {{def = "heal"}},
    customParams = {texture = "medic"},
    script = "medic.lua",
    objectname = "medic.s3o",
}

unitDefs["siege_tank"] = {
    name = "Siege Tank",
    description = "Long-range artillery with splash damage",
    maxdamage = 350,
    buildcostmetal = 300,
    buildtime = 1000,
    category = "LAND",
    footprintX = 3,
    footprintZ = 3,
    sightDistance = 400,
    movementClass = "TANK2",
    maxVelocity = 1.5,
    acceleration = 0.3,
    canAttack = true,
    weaponDefs = {
        siege_cannon = {
            name = "Siege Cannon",
            damage = {default = 60, splashDamage = 30, splashRadius = 150},
            range = 350,
            reloadtime = 3.0,
            weaponType = "Cannon",
            explosionGenerator = "explosion.s3e",
            turret = true,
        },
    },
    weapons = {{def = "siege_cannon"}},
    customParams = {texture = "siege_tank"},
    script = "siege_tank.lua",
    objectname = "siege_tank.s3o",
}

return unitDefs
